services:
  flask-app:
    build: ./app
    volumes:
      - sqlite_data:/data
      - static_volume:/app/src/website/static
      - heroes_volume:/app/src/heroes
    networks:
      - app-network

  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    volumes:
      - static_volume:/usr/share/nginx/html/static
    depends_on:
      - flask-app
    networks:
      - app-network

volumes:
  sqlite_data:
  static_volume:
  heroes_volume:

networks:
  app-network:
    driver: bridge
