services:
  flask-app:
    build: ./app
    volumes:
      - sqlite_data:/data
      - static_volume:/app/website/static
      - heroes_volume:/app/heroes
    networks:
      - app-network
    secrets:
      - access_code
      - secret_key
      - admin_pw
    environment:
      - PYTHONUNBUFFERED=1

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/usr/share/nginx/html/static
    depends_on:
      - flask-app
    networks:
      - app-network

volumes:
  sqlite_data:
  static_volume:
  heroes_volume:

networks:
  app-network:
    driver: bridge

secrets:
    access_code:
      file: ./app/secrets/access_code.txt
    secret_key:
      file: ./app/secrets/secret_key.txt
    admin_pw:
      file: ./app/secrets/admin_pw.txt
