user www-data;
worker_processes auto;
pid /run/nginx.pid;

events {
	worker_connections 4096;
	multi_accept on;
}

http {
	sendfile on;
	tcp_nopush on;
	tcp_nodelay on;
	keepalive_timeout 65;
	types_hash_max_size 2048;
	server_tokens off;

	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	ssl_protocols TLSv1.2 TLSv1.3;
	ssl_prefer_server_ciphers on;
	ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256';

	access_log /var/log/nginx/access.log;
	error_log /var/log/nginx/error.log;

	gzip on;
	gzip_types text/plain text/css application/json application/javascript text/xml;

	server {
		listen 80;
		server_name bdsm.hans.li;

		# Redirect HTTP to HTTPS
		location / {
			return 301 https://$host$request_uri;
		}
	}

	server {
		listen 443 ssl;
		server_name *.hans.li;

		ssl_certificate /etc/letsencrypt/live/hans.li/fullchain.pem;
		ssl_certificate_key /etc/letsencrypt/live/hans.li/privkey.pem;


		location / {
			proxy_pass http://flask-app:8000;
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-Forwarded-Proto $scheme;

			# Security headers
			add_header X-Content-Type-Options "nosniff";
			add_header X-Frame-Options "SAMEORIGIN";
			add_header Content-Security-Policy "default-src 'self'; style-src 'self' https://cdn.jsdelivr.net; script-src 'self' https://cdn.jsdelivr.net; font-src 'self' https://cdn.jsdelivr.net; img-src 'self' data:;";

		}

		location = /robots.txt {
			return 200 "User-agent: *\nDisallow: /\n";
		}

		location /static/ {
			alias /usr/share/nginx/html/static/;
		}

	}
}
