"""index hero lookup columns

Revision ID: e40757e367cf
Revises: bc6446d2118f
Create Date: 2026-08-29 16:03:14.281131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e40757e367cf'
down_revision = 'bc6446d2118f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hero', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hero_secure_name'), ['secure_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_hero_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hero', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hero_user_id'))
        batch_op.drop_index(batch_op.f('ix_hero_secure_name'))

    # ### end Alembic commands ###
