"""add campaign invite codes

Revision ID: eb46852faaa0
Revises: 72971a9a932f
Create Date: 2026-08-29 17:52:30.225415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb46852faaa0'
down_revision = '72971a9a932f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invite_code', sa.String(length=32), nullable=True))
        batch_op.create_index(batch_op.f('ix_campaign_invite_code'), ['invite_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_invite_code'))
        batch_op.drop_column('invite_code')

    # ### end Alembic commands ###
